# Generated by Django 2.2.3 on 2019-07-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('slug_brand', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('slug_category', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=100, verbose_name='Color')),
                ('slug_color', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_product1', models.ImageField(upload_to='products')),
                ('image_product2', models.ImageField(upload_to='products')),
                ('image_product3', models.ImageField(upload_to='products')),
                ('image_product4', models.ImageField(upload_to='products')),
                ('name_product', models.CharField(max_length=100, verbose_name='Producto')),
                ('description_product', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('stock', models.IntegerField()),
                ('slug_product', models.SlugField()),
                ('product_created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('product_updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('brand_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Brand')),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category')),
                ('color_product', models.ManyToManyField(to='catalogue.Color')),
            ],
        ),
    ]
