# Generated by Django 2.2.3 on 2019-07-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product1',
            field=models.ImageField(upload_to='products', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_product2',
            field=models.ImageField(upload_to='products', verbose_name='Primera Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_product3',
            field=models.ImageField(upload_to='products', verbose_name='Segunda Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_product4',
            field=models.ImageField(upload_to='products', verbose_name='Tercera Imagen'),
        ),
    ]
