# Generated by Django 2.2.3 on 2019-07-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190718_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_product',
            field=models.ManyToManyField(to='catalogue.Color', verbose_name='Colores disponibles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_product',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Cantidad en el inventario'),
        ),
    ]
